# Generated by Django 3.0.8 on 2023-08-15 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_auto_20230815_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='referals',
            field=models.ManyToManyField(related_name='_useraccount_referals_+', to=settings.AUTH_USER_MODEL, verbose_name='referal'),
        ),
    ]
