# Generated by Django 3.2.20 on 2023-08-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_useraccount_referals'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='referral_code',
            field=models.CharField(default='..', max_length=50),
        ),
    ]
